export const SET_ALL_SERIES = 'SET_ALL_SERIES';
export const SET_VIDEO_SERIES = 'SET_VIDEO_SERIES';
export const IS_LOADING_SERIES = 'IS_LOADING_SERIES';

export const SET_ALL_MOVIES = 'SET_ALL_MOVIES';
export const SET_VIDEO_MOVIES = 'SET_VIDEO_MOVIES';
export const IS_LOADING_MOVIES = 'IS_LOADING_MOVIES';


export const SET_SEARCH = 'SET_SEARCH';
export const SET_VIDEO_SEARCH = 'SET_VIDEO_SEARCH'
export const IS_LOADING_SEARCH = 'IS_LOADING_SEARCH';
export const SET_SEARCH_VIDEO_MOVIES = 'SET_SEARCH_VIDEO_MOVIES';

export const SET_EPISODES = 'SET_EPISODES';
export const SET_EPISODE_VIDEO = 'SET_EPISODE_VIDEO';
export const IS_LOADING_EPISODES = 'IS_LOADING_EPISODES';

export const SET_GENRES = 'SET_GENRES';
export const SET_VIDEO_GENRE_SERIE_VIDEO = 'SET_VIDEO_GENRE_SERIE_VIDEO';
export const SET_VIDEO_GENRE_MOVIE_VIDEO = 'SET_VIDEO_GENRE_MOVIE_VIDEO'
export const IS_LOADING_GENRES = 'IS_LOADING_GENRES';
